apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: core-commerce-coupon
  namespace: core-commerce
spec:
  maxReplicas: 500
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 40
        type: Utilization
    type: Resource
  minReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: core-commerce-coupon
