"""add_budget_column

Revision ID: 2d6631599944
Revises: 2bee96734b46
Create Date: 2021-12-17 17:25:07.665310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d6631599944'
down_revision = '552f5a721669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('budget', sa.Numeric(scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupon', 'budget')
    # ### end Alembic commands ###
