"""max_amount_and_min_puchase_to_numeric

Revision ID: 48be2ed35f86
Revises: 9e2b73ec0b81
Create Date: 2021-12-21 20:08:35.062991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48be2ed35f86'
down_revision = '9e2b73ec0b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coupon', 'max_amount',
                    existing_type=sa.Float(),
                    type_=sa.Numeric(scale=2),
                    existing_nullable=True)
    op.alter_column('coupon', 'min_purchase_amount',
                    existing_type=sa.Float(),
                    type_=sa.Numeric(scale=2),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coupon', 'max_amount',
                    existing_type=sa.Numeric(scale=2),
                    type_=sa.Float())
    op.alter_column('coupon', 'min_purchase_amount',
                    existing_type=sa.Numeric(scale=2),
                    type_=sa.Float())
    # ### end Alembic commands ###
