"""create_usage_history

Revision ID: 552f5a721669
Revises: 2bee96734b46
Create Date: 2021-12-16 21:01:18.050500

"""
import sqlalchemy as sa

from alembic import op
from app.db.base import CustomID

# revision identifiers, used by Alembic.
revision = '552f5a721669'
down_revision = '1851c11d35cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_primary_key("coupon_pk", "coupon", ["coupon_id", ])

    op.create_table('usage_history',
    sa.Column('id', CustomID(), server_default=sa.text("concat(CAST(EXTRACT(EPOCH FROM now()) AS BIGINT),text('-'),gen_random_uuid())"), nullable=False),
    sa.Column('transaction_id', sa.String(length=200), nullable=False),
    sa.Column('customer_key', sa.String(length=200), nullable=False),
    sa.Column('discount_amount', sa.Numeric(scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('reserved', 'confirmed', name='usagehistorystatus'), nullable=False),
    sa.Column('coupon_id', CustomID(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon.coupon_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_history')
    # ### end Alembic commands ###
