"""update_coupon_database

Revision ID: 76ee3ff01655
Revises: d1100715c10d
Create Date: 2021-12-03 12:59:49.879310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76ee3ff01655'
down_revision = 'd1100715c10d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('type', sa.String(length=60), nullable=False))
    op.add_column('coupon', sa.Column('value', sa.Float(), nullable=False))
    op.add_column('coupon', sa.Column('max_amount', sa.Float(), nullable=True))
    op.add_column('coupon', sa.Column('min_purchase_amount', sa.Float(), nullable=True))
    op.add_column('coupon', sa.Column('first_purchase', sa.Boolean(), nullable=False))
    op.drop_column('coupon', 'coupon_type')
    op.drop_column('coupon', 'coupon_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('coupon_value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('coupon', sa.Column('coupon_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('coupon', 'first_purchase')
    op.drop_column('coupon', 'min_purchase_amount')
    op.drop_column('coupon', 'max_amount')
    op.drop_column('coupon', 'value')
    op.drop_column('coupon', 'type')
    # ### end Alembic commands ###
