"""check_duplicate_index

Revision ID: 774361e3f202
Revises: be2c56dbfe85
Create Date: 2022-01-31 18:23:17.001505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774361e3f202'
down_revision = 'be2c56dbfe85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('coupon_duplicate_index', 'coupon', ['code', 'customer_key', 'valid_from', 'valid_until'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('coupon_duplicate_index', table_name='coupon')
    # ### end Alembic commands ###
