"""update_usage_history_contraints

Revision ID: 800d4c0cf00d
Revises: aee9e0aff067
Create Date: 2022-01-05 10:56:35.331632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800d4c0cf00d'
down_revision = 'aee9e0aff067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('usage_history_transaction_id_key', 'usage_history', type_='unique')
    op.create_unique_constraint('usage_history_transaction_id_coupon_id_key', 'usage_history', ['transaction_id', 'coupon_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('usage_history_transaction_id_coupon_id_key', 'usage_history', type_='unique')
    op.create_unique_constraint('usage_history_transaction_id_key', 'usage_history', ['transaction_id'])
    # ### end Alembic commands ###
