"""Create coupon model

Revision ID: 8f91ea50599f
Revises: 
Create Date: 2021-10-22 00:30:20.983850

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8f91ea50599f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coupon",
        sa.Column("coupon_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("customer_key", sa.String(length=200), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_usage", sa.Integer(), nullable=False),
        sa.Column("reserved_usage", sa.Integer(), nullable=True),
        sa.Column("confirmed_usage", sa.Integer(), nullable=True),
        sa.Column("coupon_type", sa.String(length=64), nullable=False),
        sa.Column("coupon_value", sa.Float(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("create_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_create", sa.String(length=200), nullable=True),
        sa.Column("delete_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_delete", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("coupon_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("coupon")
    # ### end Alembic commands ###
