"""remove_usage_inpuns_coupon

Revision ID: d1088b9cba5f
Revises: 490c5b0b9fb4
Create Date: 2021-12-20 14:55:40.656786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1088b9cba5f'
down_revision = '490c5b0b9fb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupon', 'reserved_usage')
    op.drop_column('coupon', 'confirmed_usage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('confirmed_usage', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('coupon', sa.Column('reserved_usage', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
