"""max_usage_is_nullable

Revision ID: d1100715c10d
Revises: 8f91ea50599f
Create Date: 2021-11-27 02:06:38.726734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1100715c10d'
down_revision = '8f91ea50599f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coupon', 'max_usage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('coupon', 'create_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coupon', 'create_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('coupon', 'max_usage',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
