apiVersion: v1
kind: Service
metadata:
  name: core-commerce-coupon
  namespace: core-commerce
spec:
  type: ClusterIP
  selector:
    app: core-commerce-coupon
  ports:
    - port: 80
      targetPort: 8000
