apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-commerce-coupon
  namespace: core-commerce
spec:
  template:
    spec:
      containers:
        - name: core-commerce-coupon
          env:
          - name: CORE_COMMERCE_COUPON_RELOAD
            value: 'True'
          - name: CORE_COMMERCE_COUPON_PEPPER
            value: 'qwert'
          - name: CORE_COMMERCE_COUPON_AUTH
            valueFrom:
              secretKeyRef:
                name: core-commerce-coupon-auth
                key: key
          - name: CORE_COMMERCE_COUPON_API_KEY
            valueFrom:
              secretKeyRef:
                name: core-commerce-coupon-api-key
                key: key
          - name: CORE_COMMERCE_COUPON_HOST
            value: '0.0.0.0'
          - name: CORE_COMMERCE_COUPON_PORT
            value: '8000'
          - name: CORE_COMMERCE_COUPON_WORKERS_COUNT
            value: '1'
          - name: CORE_COMMERCE_COUPON_DB_ECHO
            value: 'False'
          - name: CORE_COMMERCE_COUPON_BACKEND_CORS_ORIGINS
            value: '["*"]'
          - name: CORE_COMMERCE_COUPON_DB_HOST
            value: '0.0.0.0'
          - name: CORE_COMMERCE_COUPON_TIMEZONE
            value: 'America/Sao_Paulo'
          - name: CORE_COMMERCE_COUPON_DB_USER
            valueFrom:
              secretKeyRef:
                name: db-postgresql-core-commerce-coupon
                key: user
          - name: CORE_COMMERCE_COUPON_DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-postgresql-core-commerce-coupon
                key: password
          - name: CORE_COMMERCE_COUPON_DB_PORT
            valueFrom:
              secretKeyRef:
                name: db-postgresql-core-commerce-coupon
                key: port
          - name: CORE_COMMERCE_COUPON_DB_BASE
            value: "core_commerce_coupon"
          - name: CORE_COMMERCE_COUPON_LOG_LEVEL
            value: 'INFO'
          - name: CORE_COMMERCE_COUPON_JSON_LOGS
            value: 'True'

          - name: CORE_COMMERCE_COUPON_AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: core-commerce-coupon
                key: aws-access-key-id

          - name: CORE_COMMERCE_COUPON_AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: core-commerce-coupon
                key: aws-secret-access-key

          - name: CORE_COMMERCE_COUPON_AWS_REGION_NAME
            valueFrom:
              secretKeyRef:
                name: core-commerce-coupon
                key: aws-region-name

          - name: CORE_COMMERCE_COUPON_AWS_S3_BUCKET
            valueFrom:
              secretKeyRef:
                name: core-commerce-coupon
                key: aws-s3-bucket
