apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- replica_count.yaml
- cpu_ram_count.yaml
- envs.yaml
- datadog.yaml
- pgpool.yaml

resources:
- autoscale.yaml
- ingress.yaml
- job.yaml
- ./../base
